import About from '@/components/About/About'
import './globals.css'
import Resume from '@/components/Resume/Resume'
import Skills from '@/components/Skills/Skills'
import Projects from '@/components/Projects/Projects'
import Contact from '@/components/Contact/Contact'
import Navbar from '@/components/Navbar/Navbar'


export const metadata = {
  title: 'Facundo Monsegur',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <About/>
        <Resume/>
        <Skills/>
        <Projects/>
        <Contact/>
        </body>
    </html>
  )
}
